language: node_js
node_js: 
  - "8"

sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - mv .gitignore old.gitignore
  - sed '/public/,/^/d' < old.gitignore > .gitignore

script:
  - npm run build
  - /snap/bin/hugo
  - echo "6overlanders.com" >> public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python-pygments

notifications:
  email: true
