language: node_js
node_js: 
  - "8"
before_script:
  - npm install -g bower
  - npm install
  - bower install
script:
  - npm run build
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
