baseURL = "http://6overlanders.com/"
title = "6overlanders.com"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"

disableKinds = [ "taxonomy", "taxonomyTerm" ]
ignoreFiles = [ "homepage\\/.*\\.md$" ]

[blackfriday]
  hrefTargetBlank = true
