baseURL: "https://6overlanders.com/"
languageCode: "pt-br"
defaultContentLanguage: "pt-br"

Languages:
  pt-br:
    title: "6overlanders.com"
  en:
    title: "6overlanders.com"

disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS

ignoreFiles:
  - "homepage\\/.*\\.md$"

SectionPagesMenu: "main"

mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: feed/atom

outputs:
  home:
    - HTML
    - Atom

blackfriday:
  hrefTargetBlank: true

archetypeDir: src/archetypes
layoutDir: src/layouts
staticDir: src/static
themesDir: src/themes

